[tool.poetry]
name = "todo"
version = "0.1.0"
description = ""
authors = ["Jose Rodriguez <jrodriguez@bridgeinto.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pyodbc = "^4.0.39"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
